import type { TArgument } from '@core/models/Argument.model';
import type { TListDocument } from './NewOpinionArgumentsList.models';

export const initialListDocument: TListDocument = {
  id: 'root',
  items: [],
};

// Comprehensive demo data with various item types
export const demoListDocument: TListDocument = {
  id: 'root',
  items: [
    {
      id: 'item-1',
      type: 'heading1',
      title: 'The Impact of Artificial Intelligence on Society',
      index: 0,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T10:30:00'),
      },
    },
    {
      id: 'item-2',
      type: 'text',
      title:
        'As we stand at the crossroads of technological revolution, artificial intelligence has emerged as one of the most transformative forces of our time. This opinion explores the multifaceted implications of AI on modern society.',
      index: 1,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T10:32:00'),
      },
    },
    {
      id: 'item-3',
      type: 'heading2',
      title: 'Economic Transformation',
      index: 2,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T10:35:00'),
      },
    },
    {
      id: 'item-4',
      type: 'heading3',
      title: 'Job Market Disruption',
      index: 3,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T11:00:00'),
      },
    },
    {
      id: 'item-5',
      type: 'text',
      title:
        'AI-driven automation threatens to displace millions of workers across traditional industries. Manufacturing, transportation, and customer service sectors face unprecedented challenges as intelligent systems become more capable.',
      index: 4,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T11:05:00'),
      },
    },
    {
      id: 'item-6',
      type: 'argument',
      originalArgumentId: '123',
      index: 5,
      metaData: {
        author: { id: 'user-3', name: 'Elena Volkov' },
        createdDate: new Date('2024-01-15T11:20:00'),
        originalArgument: {
          id: '123',
          content: 'Studies show that AI automation could displace up to 30% of current jobs by 2030.',
          text: 'Studies show that AI automation could displace up to 30% of current jobs by 2030.',
          createdDate: '2024-01-15T11:20:00',
          author: { id: 'user-3', name: 'Elena Volkov' },
          theme: 'AI Impact',
          countComments: 5,
          countConfirmations: 12,
          countRefutations: 3,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-7',
      type: 'heading3',
      title: 'New Opportunities and Industries',
      index: 6,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T11:30:00'),
      },
    },
    {
      id: 'item-8',
      type: 'text',
      title:
        'Conversely, AI is creating entirely new categories of employment. Data scientists, AI ethicists, machine learning engineers, and AI trainers represent emerging professions that did not exist a decade ago.',
      index: 7,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T11:35:00'),
      },
    },
    {
      id: 'item-9',
      type: 'argument',
      originalArgumentId: '456',
      index: 8,
      metaData: {
        author: { id: 'user-4', name: 'James Park' },
        createdDate: new Date('2024-01-15T11:45:00'),
        originalArgument: {
          id: '456',
          content: 'The global AI market is projected to reach $1.8 trillion by 2030, creating new industries.',
          text: 'The global AI market is projected to reach $1.8 trillion by 2030, creating new industries.',
          createdDate: '2024-01-15T11:45:00',
          author: { id: 'user-4', name: 'James Park' },
          theme: 'AI Economy',
          countComments: 8,
          countConfirmations: 20,
          countRefutations: 2,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-10',
      type: 'heading3',
      title: 'Economic Inequality Concerns',
      index: 9,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T12:00:00'),
      },
    },
    {
      id: 'item-11',
      type: 'text',
      title:
        'The wealth generated by AI technologies risks concentrating in the hands of a few tech giants and their stakeholders, potentially exacerbating existing economic disparities.',
      index: 10,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T12:05:00'),
      },
    },
    {
      id: 'item-12',
      type: 'heading2',
      title: 'Social and Cultural Impact',
      index: 11,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T13:00:00'),
      },
    },
    {
      id: 'item-13',
      type: 'text',
      title:
        'Beyond economics, AI fundamentally reshapes how we interact, communicate, and perceive reality. Social media algorithms influence public discourse, while deepfakes challenge our trust in digital media.',
      index: 12,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T13:10:00'),
      },
    },
    {
      id: 'item-14',
      type: 'argument',
      originalArgumentId: '789',
      index: 13,
      metaData: {
        author: { id: 'user-5', name: 'Amara Okafor' },
        createdDate: new Date('2024-01-15T13:25:00'),
        originalArgument: {
          id: '789',
          content: 'AI-generated deepfakes have increased by 900% since 2020, posing serious misinformation risks.',
          text: 'AI-generated deepfakes have increased by 900% since 2020, posing serious misinformation risks.',
          createdDate: '2024-01-15T13:25:00',
          author: { id: 'user-5', name: 'Amara Okafor' },
          theme: 'AI Ethics',
          countComments: 15,
          countConfirmations: 30,
          countRefutations: 5,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-15',
      type: 'heading3',
      title: 'Privacy and Surveillance',
      index: 14,
      metaData: {
        author: { id: 'user-3', name: 'Elena Volkov' },
        createdDate: new Date('2024-01-15T13:40:00'),
      },
    },
    {
      id: 'item-16',
      type: 'text',
      title:
        'AI-powered surveillance systems raise profound questions about privacy rights. Facial recognition, behavioral analysis, and predictive policing technologies create unprecedented monitoring capabilities.',
      index: 15,
      metaData: {
        author: { id: 'user-3', name: 'Elena Volkov' },
        createdDate: new Date('2024-01-15T13:45:00'),
      },
    },
    {
      id: 'item-17',
      type: 'argument',
      originalArgumentId: '234',
      index: 16,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T14:00:00'),
        originalArgument: {
          id: '234',
          content: 'Facial recognition technology has an error rate of up to 35% for darker-skinned individuals.',
          text: 'Facial recognition technology has an error rate of up to 35% for darker-skinned individuals.',
          createdDate: '2024-01-15T14:00:00',
          author: { id: 'user-2', name: 'Michael Roberts' },
          theme: 'AI Bias',
          countComments: 22,
          countConfirmations: 45,
          countRefutations: 8,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-18',
      type: 'heading2',
      title: 'Ethical Considerations',
      index: 17,
      metaData: {
        author: { id: 'user-4', name: 'James Park' },
        createdDate: new Date('2024-01-15T14:30:00'),
      },
    },
    {
      id: 'item-19',
      type: 'heading3',
      title: 'Algorithmic Bias and Fairness',
      index: 18,
      metaData: {
        author: { id: 'user-4', name: 'James Park' },
        createdDate: new Date('2024-01-15T14:35:00'),
      },
    },
    {
      id: 'item-20',
      type: 'text',
      title:
        'AI systems often inherit and amplify human biases present in training data. This perpetuates discrimination in critical areas like hiring, lending, and criminal justice.',
      index: 19,
      metaData: {
        author: { id: 'user-4', name: 'James Park' },
        createdDate: new Date('2024-01-15T14:40:00'),
      },
    },
    {
      id: 'item-21',
      type: 'argument',
      originalArgumentId: '567',
      index: 20,
      metaData: {
        author: { id: 'user-5', name: 'Amara Okafor' },
        createdDate: new Date('2024-01-15T14:55:00'),
        originalArgument: {
          id: '567',
          content: 'Amazon scrapped an AI recruiting tool after it showed bias against women applicants.',
          text: 'Amazon scrapped an AI recruiting tool after it showed bias against women applicants.',
          createdDate: '2024-01-15T14:55:00',
          author: { id: 'user-5', name: 'Amara Okafor' },
          theme: 'AI Bias',
          countComments: 18,
          countConfirmations: 35,
          countRefutations: 4,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-22',
      type: 'heading3',
      title: 'Accountability and Transparency',
      index: 21,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T15:10:00'),
      },
    },
    {
      id: 'item-23',
      type: 'text',
      title:
        'As AI systems make increasingly consequential decisions, we must establish clear frameworks for accountability. Who is responsible when an autonomous vehicle causes an accident or an AI medical diagnosis proves incorrect?',
      index: 22,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T15:15:00'),
      },
    },
    {
      id: 'item-24',
      type: 'heading3',
      title: 'Environmental Impact',
      index: 23,
      metaData: {
        author: { id: 'user-3', name: 'Elena Volkov' },
        createdDate: new Date('2024-01-15T15:30:00'),
      },
    },
    {
      id: 'item-25',
      type: 'text',
      title:
        'Training large AI models requires massive computational resources, consuming enormous amounts of energy and contributing to carbon emissions. We must balance technological progress with environmental sustainability.',
      index: 24,
      metaData: {
        author: { id: 'user-3', name: 'Elena Volkov' },
        createdDate: new Date('2024-01-15T15:35:00'),
      },
    },
    {
      id: 'item-26',
      type: 'argument',
      originalArgumentId: '890',
      index: 25,
      metaData: {
        author: { id: 'user-2', name: 'Michael Roberts' },
        createdDate: new Date('2024-01-15T15:50:00'),
        originalArgument: {
          id: '890',
          content: 'Training GPT-4 consumed an estimated 50 GWh of electricity, equivalent to powering 4,600 US homes for a year.',
          text: 'Training GPT-4 consumed an estimated 50 GWh of electricity, equivalent to powering 4,600 US homes for a year.',
          createdDate: '2024-01-15T15:50:00',
          author: { id: 'user-2', name: 'Michael Roberts' },
          theme: 'AI Environment',
          countComments: 10,
          countConfirmations: 25,
          countRefutations: 6,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-27',
      type: 'heading2',
      title: 'Looking Forward',
      index: 26,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T16:00:00'),
      },
    },
    {
      id: 'item-28',
      type: 'text',
      title:
        "The future of AI in society depends on the choices we make today. Through thoughtful regulation, ethical guidelines, and inclusive development practices, we can harness AI's potential while mitigating its risks.",
      index: 27,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T16:10:00'),
      },
    },
    {
      id: 'item-29',
      type: 'argument',
      originalArgumentId: '345',
      index: 28,
      metaData: {
        author: { id: 'user-4', name: 'James Park' },
        createdDate: new Date('2024-01-15T16:20:00'),
        originalArgument: {
          id: '345',
          content: 'International cooperation on AI governance could prevent an AI arms race between nations.',
          text: 'International cooperation on AI governance could prevent an AI arms race between nations.',
          createdDate: '2024-01-15T16:20:00',
          author: { id: 'user-4', name: 'James Park' },
          theme: 'AI Governance',
          countComments: 12,
          countConfirmations: 28,
          countRefutations: 7,
        } satisfies TArgument,
      },
    },
    {
      id: 'item-30',
      type: 'heading3',
      title: 'A Call for Collaborative Action',
      index: 29,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T16:30:00'),
      },
    },
    {
      id: 'item-31',
      type: 'text',
      title:
        "Addressing these challenges requires collaboration between technologists, policymakers, ethicists, and civil society. Only through collective effort can we ensure AI serves humanity's best interests.",
      index: 30,
      metaData: {
        author: { id: 'user-1', name: 'Sarah Chen' },
        createdDate: new Date('2024-01-15T16:35:00'),
      },
    },
  ],
};
